### PR TITLE
fix: WorldLocationFromTreeID() for condition that was causing exception

### PR DESCRIPTION
**Pull request by Louspirit**
Exception was "Depth higher than Octree Depth" in GetVoxelSizeByDepth().

Change is at line 391.

### CODE REVIEW

**Comment by NonStaticGH** [comment]
Hello, I'm sorry to say that I will not review/accept any github changes to
my project, that would require me to treat this free plugin as my second
job. If you found a bug, please provide reproduction steps. This function
was unit tested on all proper treeID's in a depth 3 Octree, so please make
sure you're passing a correct TreeID.

**Comment by Louspirit** [comment]
You are welcome to take your time reviewing the PR. Isn't participation from the community a potential gain of time/scope/stability to the product you publicly released?😉

I just changed `<=` to `<` where I believe the only for loop followed by a `GetVoxelSizeByDepth()` method.

Because with this condition, let's say octree depth is set to 2: the for loop will let pass one time too many and set currDepth to 3. Which is over the octree depth, causing the error.

**Comment by Louspirit** [comment]
Can I suggest implementing labels for the Github repo?  It could help sorting and prioritize PR and issues. In this case, something like `BugFix`.

**Comment by NonStaticGH** [comment]
You are wrong, and this is not the way to report bugs. Please provide the issue description and steps to reproduce, in engine, without making any changes in the code. You are free to modify your local copy of the plugin, but I will not be accepting pull requests.

**Pull request closed without merging**
